{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 24,
   "metadata": {},
   "outputs": [],
   "source": [
    "import sagemaker\n",
    "from sagemaker import get_execution_role\n",
    "from sagemaker.s3 import S3Uploader\n",
    "from sagemaker.pytorch import PyTorch\n",
    "\n",
    "import os\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.model_selection import train_test_split "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "metadata": {},
   "outputs": [],
   "source": [
    "sagemaker_session = sagemaker.Session()\n",
    "role = get_execution_role()\n",
    "region = sagemaker_session.boto_session.region_name"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "metadata": {},
   "outputs": [],
   "source": [
    "pytorch_estimator = PyTorch(entry_point = 'train.py',\n",
    "                            source_dir = '../scripts'\n",
    "                            instance_type='ml.p3.2xlarge',\n",
    "                            role = role,\n",
    "                            instance_count=1,\n",
    "                            framework_version='1.8.0',\n",
    "                            py_version='py3',\n",
    "                            hyperparameters = {'epochs': 100, \n",
    "                                               'batch-size': 64, \n",
    "                                               'learning-rate': 0.003})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "2022-02-28 19:12:34 Starting - Starting the training job...\n",
      "2022-02-28 19:12:36 Starting - Launching requested ML instancesProfilerReport-1646075553: InProgress\n",
      ".........\n",
      "2022-02-28 19:14:27 Starting - Preparing the instances for training......\n",
      "2022-02-28 19:15:28 Downloading - Downloading input data\n",
      "2022-02-28 19:15:28 Training - Downloading the training image..............................\n",
      "2022-02-28 19:20:29 Training - Training image download completed. Training in progress.\u001b[34mbash: cannot set terminal process group (-1): Inappropriate ioctl for device\u001b[0m\n",
      "\u001b[34mbash: no job control in this shell\u001b[0m\n",
      "\u001b[34m2022-02-28 19:20:26,776 sagemaker-training-toolkit INFO     Imported framework sagemaker_pytorch_container.training\u001b[0m\n",
      "\u001b[34m2022-02-28 19:20:26,800 sagemaker_pytorch_container.training INFO     Block until all host DNS lookups succeed.\u001b[0m\n",
      "\u001b[34m2022-02-28 19:20:28,225 sagemaker_pytorch_container.training INFO     Invoking user training script.\u001b[0m\n",
      "\u001b[34m2022-02-28 19:20:28,793 sagemaker-training-toolkit INFO     Invoking user script\u001b[0m\n",
      "\u001b[34mTraining Env:\u001b[0m\n",
      "\u001b[34m{\n",
      "    \"additional_framework_parameters\": {},\n",
      "    \"channel_input_dirs\": {\n",
      "        \"train\": \"/opt/ml/input/data/train\"\n",
      "    },\n",
      "    \"current_host\": \"algo-1\",\n",
      "    \"framework_module\": \"sagemaker_pytorch_container.training:main\",\n",
      "    \"hosts\": [\n",
      "        \"algo-1\"\n",
      "    ],\n",
      "    \"hyperparameters\": {\n",
      "        \"batch-size\": 64,\n",
      "        \"learning-rate\": 0.003,\n",
      "        \"epochs\": 100\n",
      "    },\n",
      "    \"input_config_dir\": \"/opt/ml/input/config\",\n",
      "    \"input_data_config\": {\n",
      "        \"train\": {\n",
      "            \"TrainingInputMode\": \"File\",\n",
      "            \"S3DistributionType\": \"FullyReplicated\",\n",
      "            \"RecordWrapperType\": \"None\"\n",
      "        }\n",
      "    },\n",
      "    \"input_dir\": \"/opt/ml/input\",\n",
      "    \"is_master\": true,\n",
      "    \"job_name\": \"pytorch-training-2022-02-28-19-12-33-865\",\n",
      "    \"log_level\": 20,\n",
      "    \"master_hostname\": \"algo-1\",\n",
      "    \"model_dir\": \"/opt/ml/model\",\n",
      "    \"module_dir\": \"s3://sagemaker-us-east-1-247385444016/pytorch-training-2022-02-28-19-12-33-865/source/sourcedir.tar.gz\",\n",
      "    \"module_name\": \"churn\",\n",
      "    \"network_interface_name\": \"eth0\",\n",
      "    \"num_cpus\": 8,\n",
      "    \"num_gpus\": 1,\n",
      "    \"output_data_dir\": \"/opt/ml/output/data\",\n",
      "    \"output_dir\": \"/opt/ml/output\",\n",
      "    \"output_intermediate_dir\": \"/opt/ml/output/intermediate\",\n",
      "    \"resource_config\": {\n",
      "        \"current_host\": \"algo-1\",\n",
      "        \"hosts\": [\n",
      "            \"algo-1\"\n",
      "        ],\n",
      "        \"network_interface_name\": \"eth0\"\n",
      "    },\n",
      "    \"user_entry_point\": \"churn.py\"\u001b[0m\n",
      "\u001b[34m}\u001b[0m\n",
      "\u001b[34mEnvironment variables:\u001b[0m\n",
      "\u001b[34mSM_HOSTS=[\"algo-1\"]\u001b[0m\n",
      "\u001b[34mSM_NETWORK_INTERFACE_NAME=eth0\u001b[0m\n",
      "\u001b[34mSM_HPS={\"batch-size\":64,\"epochs\":100,\"learning-rate\":0.003}\u001b[0m\n",
      "\u001b[34mSM_USER_ENTRY_POINT=churn.py\u001b[0m\n",
      "\u001b[34mSM_FRAMEWORK_PARAMS={}\u001b[0m\n",
      "\u001b[34mSM_RESOURCE_CONFIG={\"current_host\":\"algo-1\",\"hosts\":[\"algo-1\"],\"network_interface_name\":\"eth0\"}\u001b[0m\n",
      "\u001b[34mSM_INPUT_DATA_CONFIG={\"train\":{\"RecordWrapperType\":\"None\",\"S3DistributionType\":\"FullyReplicated\",\"TrainingInputMode\":\"File\"}}\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_DATA_DIR=/opt/ml/output/data\u001b[0m\n",
      "\u001b[34mSM_CHANNELS=[\"train\"]\u001b[0m\n",
      "\u001b[34mSM_CURRENT_HOST=algo-1\u001b[0m\n",
      "\u001b[34mSM_MODULE_NAME=churn\u001b[0m\n",
      "\u001b[34mSM_LOG_LEVEL=20\u001b[0m\n",
      "\u001b[34mSM_FRAMEWORK_MODULE=sagemaker_pytorch_container.training:main\u001b[0m\n",
      "\u001b[34mSM_INPUT_DIR=/opt/ml/input\u001b[0m\n",
      "\u001b[34mSM_INPUT_CONFIG_DIR=/opt/ml/input/config\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_DIR=/opt/ml/output\u001b[0m\n",
      "\u001b[34mSM_NUM_CPUS=8\u001b[0m\n",
      "\u001b[34mSM_NUM_GPUS=1\u001b[0m\n",
      "\u001b[34mSM_MODEL_DIR=/opt/ml/model\u001b[0m\n",
      "\u001b[34mSM_MODULE_DIR=s3://sagemaker-us-east-1-247385444016/pytorch-training-2022-02-28-19-12-33-865/source/sourcedir.tar.gz\u001b[0m\n",
      "\u001b[34mSM_TRAINING_ENV={\"additional_framework_parameters\":{},\"channel_input_dirs\":{\"train\":\"/opt/ml/input/data/train\"},\"current_host\":\"algo-1\",\"framework_module\":\"sagemaker_pytorch_container.training:main\",\"hosts\":[\"algo-1\"],\"hyperparameters\":{\"batch-size\":64,\"epochs\":100,\"learning-rate\":0.003},\"input_config_dir\":\"/opt/ml/input/config\",\"input_data_config\":{\"train\":{\"RecordWrapperType\":\"None\",\"S3DistributionType\":\"FullyReplicated\",\"TrainingInputMode\":\"File\"}},\"input_dir\":\"/opt/ml/input\",\"is_master\":true,\"job_name\":\"pytorch-training-2022-02-28-19-12-33-865\",\"log_level\":20,\"master_hostname\":\"algo-1\",\"model_dir\":\"/opt/ml/model\",\"module_dir\":\"s3://sagemaker-us-east-1-247385444016/pytorch-training-2022-02-28-19-12-33-865/source/sourcedir.tar.gz\",\"module_name\":\"churn\",\"network_interface_name\":\"eth0\",\"num_cpus\":8,\"num_gpus\":1,\"output_data_dir\":\"/opt/ml/output/data\",\"output_dir\":\"/opt/ml/output\",\"output_intermediate_dir\":\"/opt/ml/output/intermediate\",\"resource_config\":{\"current_host\":\"algo-1\",\"hosts\":[\"algo-1\"],\"network_interface_name\":\"eth0\"},\"user_entry_point\":\"churn.py\"}\u001b[0m\n",
      "\u001b[34mSM_USER_ARGS=[\"--batch-size\",\"64\",\"--epochs\",\"100\",\"--learning-rate\",\"0.003\"]\u001b[0m\n",
      "\u001b[34mSM_OUTPUT_INTERMEDIATE_DIR=/opt/ml/output/intermediate\u001b[0m\n",
      "\u001b[34mSM_CHANNEL_TRAIN=/opt/ml/input/data/train\u001b[0m\n",
      "\u001b[34mSM_HP_BATCH-SIZE=64\u001b[0m\n",
      "\u001b[34mSM_HP_LEARNING-RATE=0.003\u001b[0m\n",
      "\u001b[34mSM_HP_EPOCHS=100\u001b[0m\n",
      "\u001b[34mPYTHONPATH=/opt/ml/code:/opt/conda/bin:/opt/conda/lib/python36.zip:/opt/conda/lib/python3.6:/opt/conda/lib/python3.6/lib-dynload:/opt/conda/lib/python3.6/site-packages\u001b[0m\n",
      "\u001b[34mInvoking script with the following command:\u001b[0m\n",
      "\u001b[34m/opt/conda/bin/python3.6 churn.py --batch-size 64 --epochs 100 --learning-rate 0.003\u001b[0m\n",
      "\u001b[34mNamespace(current_host='algo-1', hosts=['algo-1'], model_dir='/opt/ml/model', output_data_dir='/opt/ml/output/data', sm_model_dir='/opt/ml/model', train='/opt/ml/input/data/train')\u001b[0m\n",
      "\u001b[34m/opt/ml/input/data/train\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.017 algo-1:26 INFO utils.py:27] RULE_JOB_STOP_SIGNAL_FILENAME: None\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.162 algo-1:26 INFO profiler_config_parser.py:102] User has disabled profiler.\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.163 algo-1:26 INFO json_config.py:91] Creating hook from json_config at /opt/ml/input/config/debughookconfig.json.\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.163 algo-1:26 INFO hook.py:199] tensorboard_dir has not been set for the hook. SMDebug will not be exporting tensorboard summaries.\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.164 algo-1:26 INFO hook.py:253] Saving to /opt/ml/output/tensors\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.164 algo-1:26 INFO state_store.py:77] The checkpoint config file /opt/ml/input/config/checkpointconfig.json does not exist.\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.599 algo-1:26 INFO hook.py:584] name:0.weight count_params:832\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.599 algo-1:26 INFO hook.py:584] name:0.bias count_params:64\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.600 algo-1:26 INFO hook.py:584] name:2.weight count_params:4096\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.600 algo-1:26 INFO hook.py:584] name:2.bias count_params:64\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.600 algo-1:26 INFO hook.py:584] name:4.weight count_params:64\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.600 algo-1:26 INFO hook.py:584] name:4.bias count_params:1\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.600 algo-1:26 INFO hook.py:586] Total Trainable Params: 5121\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.600 algo-1:26 INFO hook.py:413] Monitoring the collections: losses\u001b[0m\n",
      "\u001b[34m[2022-02-28 19:20:33.603 algo-1:26 INFO hook.py:476] Hook is writing from the hook with pid: 26\u001b[0m\n",
      "\u001b[34mEpoch 0 - Training loss: 0.43726603044196966\u001b[0m\n",
      "\u001b[34mEpoch 1 - Training loss: 0.3576710416935384\u001b[0m\n",
      "\u001b[34mEpoch 2 - Training loss: 0.33914266908541324\u001b[0m\n",
      "\u001b[34mEpoch 3 - Training loss: 0.3323130869306624\u001b[0m\n",
      "\u001b[34mEpoch 4 - Training loss: 0.3292907426133752\u001b[0m\n",
      "\u001b[34mEpoch 5 - Training loss: 0.3258932107128203\u001b[0m\n",
      "\u001b[34mEpoch 6 - Training loss: 0.32363252313807606\u001b[0m\n",
      "\u001b[34mEpoch 7 - Training loss: 0.3225824484601617\u001b[0m\n",
      "\u001b[34mEpoch 8 - Training loss: 0.3205693163909018\u001b[0m\n",
      "\u001b[34mEpoch 9 - Training loss: 0.31880625286139547\u001b[0m\n",
      "\u001b[34mEpoch 10 - Training loss: 0.31691677439957855\u001b[0m\n",
      "\u001b[34mEpoch 11 - Training loss: 0.3179988564457744\u001b[0m\n",
      "\u001b[34mEpoch 12 - Training loss: 0.31452031172811984\u001b[0m\n",
      "\u001b[34mEpoch 13 - Training loss: 0.31342993886210024\u001b[0m\n",
      "\u001b[34mEpoch 14 - Training loss: 0.31256052013486624\u001b[0m\n",
      "\u001b[34mEpoch 15 - Training loss: 0.30983347008004786\u001b[0m\n",
      "\u001b[34mEpoch 16 - Training loss: 0.30888627930544316\u001b[0m\n",
      "\u001b[34mEpoch 17 - Training loss: 0.30853569209575654\u001b[0m\n",
      "\u001b[34mEpoch 18 - Training loss: 0.3076091418042779\u001b[0m\n",
      "\u001b[34mEpoch 19 - Training loss: 0.3068100023083389\u001b[0m\n",
      "\u001b[34mEpoch 20 - Training loss: 0.30468046297319235\u001b[0m\n",
      "\u001b[34mEpoch 21 - Training loss: 0.30326836062595247\u001b[0m\n",
      "\u001b[34mEpoch 22 - Training loss: 0.29990750914439557\u001b[0m\n",
      "\u001b[34mEpoch 23 - Training loss: 0.2983188958372921\u001b[0m\n",
      "\u001b[34mEpoch 24 - Training loss: 0.2970258506480604\u001b[0m\n",
      "\u001b[34mEpoch 25 - Training loss: 0.2966073320247233\u001b[0m\n",
      "\u001b[34mEpoch 26 - Training loss: 0.2947651526890695\u001b[0m\n",
      "\u001b[34mEpoch 27 - Training loss: 0.2908246916718781\u001b[0m\n",
      "\u001b[34mEpoch 28 - Training loss: 0.28998794802464545\u001b[0m\n",
      "\u001b[34mEpoch 29 - Training loss: 0.29172039800323546\u001b[0m\n",
      "\u001b[34mEpoch 30 - Training loss: 0.2859232857357711\u001b[0m\n",
      "\u001b[34mEpoch 31 - Training loss: 0.2847970805130899\u001b[0m\n",
      "\u001b[34mEpoch 32 - Training loss: 0.28337392769753933\u001b[0m\n",
      "\u001b[34mEpoch 33 - Training loss: 0.2815882802940905\u001b[0m\n",
      "\u001b[34mEpoch 34 - Training loss: 0.27795729227364063\u001b[0m\n",
      "\u001b[34mEpoch 35 - Training loss: 0.27959277951158584\u001b[0m\n",
      "\u001b[34mEpoch 36 - Training loss: 0.27442575921304524\u001b[0m\n",
      "\u001b[34mEpoch 37 - Training loss: 0.2730200029909611\u001b[0m\n",
      "\u001b[34mEpoch 38 - Training loss: 0.271102630905807\u001b[0m\n",
      "\u001b[34mEpoch 39 - Training loss: 0.27226037383079527\u001b[0m\n",
      "\u001b[34mEpoch 40 - Training loss: 0.2671817837748677\u001b[0m\n",
      "\u001b[34mEpoch 41 - Training loss: 0.26640260736458005\u001b[0m\n",
      "\u001b[34mEpoch 42 - Training loss: 0.2624500480014831\u001b[0m\n",
      "\u001b[34mEpoch 43 - Training loss: 0.26105002756230533\u001b[0m\n",
      "\u001b[34mEpoch 44 - Training loss: 0.2600953231099993\u001b[0m\n",
      "\u001b[34mEpoch 45 - Training loss: 0.2587096369359642\u001b[0m\n",
      "\u001b[34mEpoch 46 - Training loss: 0.2586809016764164\u001b[0m\n",
      "\u001b[34mEpoch 47 - Training loss: 0.25720385783351957\u001b[0m\n",
      "\u001b[34mEpoch 48 - Training loss: 0.25590252596884966\u001b[0m\n",
      "\u001b[34mEpoch 49 - Training loss: 0.2529623470734805\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"churn.py\", line 148, in <module>\n",
      "    model.save(os.path.join(args.sm_model_dir, '000000001'))\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 977, in __getattr__\n",
      "    type(self).__name__, name))\u001b[0m\n",
      "\u001b[34mAttributeError: 'Sequential' object has no attribute 'save'\u001b[0m\n",
      "\u001b[34m2022-02-28 19:21:44,374 sagemaker-training-toolkit ERROR    ExecuteUserScriptError:\u001b[0m\n",
      "\u001b[34mCommand \"/opt/conda/bin/python3.6 churn.py --batch-size 64 --epochs 100 --learning-rate 0.003\"\u001b[0m\n",
      "\u001b[34mTraceback (most recent call last):\n",
      "  File \"churn.py\", line 148, in <module>\n",
      "    model.save(os.path.join(args.sm_model_dir, '000000001'))\n",
      "  File \"/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 977, in __getattr__\n",
      "    type(self).__name__, name))\u001b[0m\n",
      "\u001b[34mAttributeError: 'Sequential' object has no attribute 'save'\u001b[0m\n",
      "\n",
      "2022-02-28 19:22:11 Uploading - Uploading generated training model\n",
      "2022-02-28 19:22:11 Failed - Training job failed\n",
      "ProfilerReport-1646075553: Stopping\n"
     ]
    },
    {
     "ename": "UnexpectedStatusException",
     "evalue": "Error for Training job pytorch-training-2022-02-28-19-12-33-865: Failed. Reason: AlgorithmError: ExecuteUserScriptError:\nCommand \"/opt/conda/bin/python3.6 churn.py --batch-size 64 --epochs 100 --learning-rate 0.003\"\nTraceback (most recent call last):\n  File \"churn.py\", line 148, in <module>\n    model.save(os.path.join(args.sm_model_dir, '000000001'))\n  File \"/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 977, in __getattr__\n    type(self).__name__, name))\nAttributeError: 'Sequential' object has no attribute 'save'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-28-ec3767a4dfe6>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mpytorch_estimator\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mfit\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m{\u001b[0m\u001b[0;34m'train'\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;34m's3://responsibleai/data/churn.csv'\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m",
      "\u001b[0;32m/opt/conda/lib/python3.6/site-packages/sagemaker/estimator.py\u001b[0m in \u001b[0;36mfit\u001b[0;34m(self, inputs, wait, logs, job_name, experiment_config)\u001b[0m\n\u001b[1;32m    690\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjobs\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mappend\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlatest_training_job\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    691\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 692\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlatest_training_job\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    693\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    694\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_compilation_job_name\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/opt/conda/lib/python3.6/site-packages/sagemaker/estimator.py\u001b[0m in \u001b[0;36mwait\u001b[0;34m(self, logs)\u001b[0m\n\u001b[1;32m   1653\u001b[0m         \u001b[0;31m# If logs are requested, call logs_for_jobs.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1654\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mlogs\u001b[0m \u001b[0;34m!=\u001b[0m \u001b[0;34m\"None\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1655\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mlogs_for_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mTrue\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mlog_type\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mlogs\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1656\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1657\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0msagemaker_session\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mwait_for_job\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/opt/conda/lib/python3.6/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36mlogs_for_job\u001b[0;34m(self, job_name, wait, poll, log_type)\u001b[0m\n\u001b[1;32m   3777\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3778\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mwait\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 3779\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_check_job_status\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mjob_name\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdescription\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"TrainingJobStatus\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   3780\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mdot\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   3781\u001b[0m                 \u001b[0mprint\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m/opt/conda/lib/python3.6/site-packages/sagemaker/session.py\u001b[0m in \u001b[0;36m_check_job_status\u001b[0;34m(self, job, desc, status_key_name)\u001b[0m\n\u001b[1;32m   3336\u001b[0m                 ),\n\u001b[1;32m   3337\u001b[0m                 \u001b[0mallowed_statuses\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"Completed\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m\"Stopped\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 3338\u001b[0;31m                 \u001b[0mactual_status\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0mstatus\u001b[0m\u001b[0;34m,\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   3339\u001b[0m             )\n\u001b[1;32m   3340\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mUnexpectedStatusException\u001b[0m: Error for Training job pytorch-training-2022-02-28-19-12-33-865: Failed. Reason: AlgorithmError: ExecuteUserScriptError:\nCommand \"/opt/conda/bin/python3.6 churn.py --batch-size 64 --epochs 100 --learning-rate 0.003\"\nTraceback (most recent call last):\n  File \"churn.py\", line 148, in <module>\n    model.save(os.path.join(args.sm_model_dir, '000000001'))\n  File \"/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py\", line 977, in __getattr__\n    type(self).__name__, name))\nAttributeError: 'Sequential' object has no attribute 'save'"
     ]
    }
   ],
   "source": [
    "pytorch_estimator.fit({'train': 's3://responsibleai/data/churn.csv'})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "instance_type": "ml.g4dn.xlarge",
  "kernelspec": {
   "display_name": "Python 3 (PyTorch 1.8 Python 3.6 GPU Optimized)",
   "language": "python",
   "name": "python3__SAGEMAKER_INTERNAL__arn:aws:sagemaker:us-east-1:081325390199:image/pytorch-1.8-gpu-py36"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.6.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}
